services:
  db:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    networks:
      - app-network

  server:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB=postgres://postgres:12345@db:5432/testdb
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network:
    driver: bridge 
